name: nodejs CICD workflow
run-name: nodejs CICD workflow
on:
 push:
  branches:
   main
jobs:
 build-artifact-image:
  runs-on: ubuntu-latest
  steps:
   
   - name: checkout code
     uses: actions/checkout@v4.2.2

   - name: Use Node.js 20
     uses: actions/setup-node@v4
     with:
        node-version: 20
   - run: npm ci
   - run: npm run lint
   - run: npm run test:coverage
   - run: npx codecov
     continue-on-error: true   
 
   - name: Build application
     run: npm run build
     
   - name: upload artifact  
     uses: actions/upload-artifact@v4.6.0
     with:
       name: build-artifact
       path: ./
      
   - name: Build docker image
     run: |
      docker build -t nodejs-image .
      docker tag java-maven-image:latest ${{ vars.DOCKER_USERNAME }}/nodejs-image
      
   - name: Login to DockerHub
     env:
      username: ${{ vars.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
     uses: docker/login-action@v2
     with:
        username: ${{ env.username }}
        password: ${{ env.password }}

   - name: Push Docker image
     run: |
       docker push ${{ vars.DOCKER_USERNAME }}/nodejs-image
       
 deploymet:
  needs: build-artifact-image
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4.2.2
     
   - name: minikube setup
     uses: medyagh/setup-minikube@v0.0.16
     with:
      version: 1.33.0
      
   - name: start minikube
     run: |
      minikube start
      
   - name: Deploy to Minikube
     run: |
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml
      
   - name: Sleep for 30 seconds
     run: sleep 30s
     shell: bash   
     
   - name: Verify deployment
     run: |
      kubectl get pods 
      kubectl get svc
        
